before_install:
 - sudo add-apt-repository ppa:trevorbernard/zeromq -y
 - sudo apt-get update -y
 - sudo apt-get install libzmq3-dev libpgm-dev -y
 - sudo dpkg -i debs/jzmq_2.1.1-1_amd64.deb

language: java

script: mvn test

jdk:
 - openjdk6
 - openjdk7
